# Example ingress for skra
# Note: ingress controller runs in bifrost-platform namespace
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: skra
  namespace: skra
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
spec:
  ingressClassName: nginx
  rules:
    - host: dev.docs.midtowntg.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: skra-api
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: skra-client
                port:
                  number: 80
  tls:
    - hosts:
        - dev.docs.midtowntg.com
      secretName: skra-tls
