"""Unit tests for checklist/SOP custom asset fields (issue #37).

Covers definition validation, value shape validation, server-owned
completion stamping, item-level merge (concurrency-safe updates), and
completion-history preservation across definition edits.
"""

from datetime import UTC, datetime
from uuid import uuid4

import pytest

from src.models.contracts.custom_asset import ChecklistItemDefinition, FieldDefinition
from src.services.custom_asset_validation import (
    CustomAssetValidationError,
    initialize_checklist_values,
    merge_checklist_value,
    validate_field_definitions,
    validate_values,
)


def _checklist_field(**kwargs):
    defaults = {
        "key": "sop",
        "name": "SOP",
        "type": "checklist",
        "checklist_items": [
            ChecklistItemDefinition(id="step-1", label="Disable account"),
            ChecklistItemDefinition(id="step-2", label="Revoke tokens", required=True),
        ],
    }
    defaults.update(kwargs)
    return FieldDefinition(**defaults)


class TestChecklistDefinitionValidation:
    def test_valid_checklist_passes(self):
        validate_field_definitions([_checklist_field()])

    def test_checklist_requires_items(self):
        with pytest.raises(ValueError, match="at least one item"):
            FieldDefinition(key="sop", name="SOP", type="checklist", checklist_items=[])

    def test_checklist_rejects_blank_labels(self):
        with pytest.raises(ValueError, match="non-empty labels"):
            FieldDefinition(
                key="sop",
                name="SOP",
                type="checklist",
                checklist_items=[ChecklistItemDefinition(id="a", label="  ")],
            )

    def test_checklist_rejects_duplicate_item_ids(self):
        with pytest.raises(ValueError, match="unique"):
            FieldDefinition(
                key="sop",
                name="SOP",
                type="checklist",
                checklist_items=[
                    ChecklistItemDefinition(id="a", label="One"),
                    ChecklistItemDefinition(id="a", label="Two"),
                ],
            )

    def test_item_ids_autogenerated_when_missing(self):
        field = FieldDefinition(
            key="sop",
            name="SOP",
            type="checklist",
            checklist_items=[ChecklistItemDefinition(label="Only step")],
        )
        assert field.checklist_items[0].id

    def test_non_checklist_ignores_missing_items(self):
        validate_field_definitions([FieldDefinition(key="t", name="T", type="text")])


class TestChecklistValueValidation:
    def test_valid_value_passes(self):
        field = _checklist_field()
        validate_values(
            [field],
            {"sop": {"items": [{"id": "step-1", "completed": True}]}},
            partial=True,
        )

    def test_rejects_non_dict(self):
        with pytest.raises(CustomAssetValidationError, match="object"):
            validate_values([_checklist_field()], {"sop": [1, 2]}, partial=True)

    def test_rejects_unknown_item_id(self):
        with pytest.raises(CustomAssetValidationError, match="unknown checklist item"):
            validate_values(
                [_checklist_field()],
                {"sop": {"items": [{"id": "nope", "completed": True}]}},
                partial=True,
            )

    def test_rejects_non_bool_completed(self):
        with pytest.raises(CustomAssetValidationError, match="boolean"):
            validate_values(
                [_checklist_field()],
                {"sop": {"items": [{"id": "step-1", "completed": "yes"}]}},
                partial=True,
            )

    def test_client_stamps_do_not_fail_validation(self):
        # Stamps are ignored server-side, never rejected at validation.
        validate_values(
            [_checklist_field()],
            {
                "sop": {
                    "items": [
                        {
                            "id": "step-1",
                            "completed": True,
                            "completed_by": "attacker",
                            "completed_at": "2000-01-01T00:00:00",
                        }
                    ]
                }
            },
            partial=True,
        )


class TestChecklistMerge:
    USER_A = uuid4()
    USER_B = uuid4()
    NOW = datetime(2026, 5, 1, 12, 0, 0, tzinfo=UTC)

    def test_new_completion_is_server_stamped(self):
        merged = merge_checklist_value(
            _checklist_field(),
            {"items": []},
            {"items": [{"id": "step-1", "completed": True}]},
            self.USER_A,
            self.NOW,
        )
        (entry,) = [e for e in merged["items"] if e["id"] == "step-1"]
        assert entry["completed"] is True
        assert entry["completed_by"] == str(self.USER_A)
        assert entry["completed_at"] == self.NOW.isoformat()

    def test_client_stamps_are_overwritten(self):
        merged = merge_checklist_value(
            _checklist_field(),
            {"items": []},
            {
                "items": [
                    {
                        "id": "step-1",
                        "completed": True,
                        "completed_by": "attacker",
                        "completed_at": "2000-01-01T00:00:00",
                    }
                ]
            },
            self.USER_A,
            self.NOW,
        )
        (entry,) = [e for e in merged["items"] if e["id"] == "step-1"]
        assert entry["completed_by"] == str(self.USER_A)
        assert entry["completed_at"] == self.NOW.isoformat()

    def test_persisting_completion_keeps_original_stamp(self):
        stored = {
            "items": [
                {
                    "id": "step-1",
                    "completed": True,
                    "completed_by": str(self.USER_A),
                    "completed_at": "2026-04-01T10:00:00+00:00",
                }
            ]
        }
        merged = merge_checklist_value(
            _checklist_field(),
            stored,
            {"items": [{"id": "step-1", "completed": True}]},
            self.USER_B,
            self.NOW,
        )
        (entry,) = [e for e in merged["items"] if e["id"] == "step-1"]
        assert entry["completed_by"] == str(self.USER_A)
        assert entry["completed_at"] == "2026-04-01T10:00:00+00:00"

    def test_uncomplete_clears_stamp(self):
        stored = {
            "items": [
                {
                    "id": "step-1",
                    "completed": True,
                    "completed_by": str(self.USER_A),
                    "completed_at": "2026-04-01T10:00:00+00:00",
                }
            ]
        }
        merged = merge_checklist_value(
            _checklist_field(),
            stored,
            {"items": [{"id": "step-1", "completed": False}]},
            self.USER_B,
            self.NOW,
        )
        (entry,) = [e for e in merged["items"] if e["id"] == "step-1"]
        assert entry == {"id": "step-1", "completed": False}

    def test_absent_items_keep_state_concurrent_toggles_survive(self):
        # Two writers toggle different items: each sends only their item,
        # the other's stored state must survive the merge.
        stored = {
            "items": [
                {
                    "id": "step-1",
                    "completed": True,
                    "completed_by": str(self.USER_A),
                    "completed_at": "2026-04-01T10:00:00+00:00",
                }
            ]
        }
        merged = merge_checklist_value(
            _checklist_field(),
            stored,
            {"items": [{"id": "step-2", "completed": True}]},
            self.USER_B,
            self.NOW,
        )
        by_id = {e["id"]: e for e in merged["items"]}
        assert by_id["step-1"]["completed"] is True
        assert by_id["step-1"]["completed_by"] == str(self.USER_A)
        assert by_id["step-2"]["completed_by"] == str(self.USER_B)

    def test_removed_definition_items_keep_history(self):
        field = _checklist_field(
            checklist_items=[ChecklistItemDefinition(id="step-1", label="Kept")]
        )
        stored = {
            "items": [
                {
                    "id": "step-1",
                    "completed": True,
                    "completed_by": str(self.USER_A),
                    "completed_at": "2026-04-01T10:00:00+00:00",
                },
                {
                    "id": "step-old",
                    "completed": True,
                    "completed_by": str(self.USER_A),
                    "completed_at": "2026-03-01T10:00:00+00:00",
                },
            ]
        }
        merged = merge_checklist_value(field, stored, {"items": []}, self.USER_B, self.NOW)
        by_id = {e["id"]: e for e in merged["items"]}
        assert by_id["step-old"]["completed"] is True
        assert by_id["step-old"]["completed_at"] == "2026-03-01T10:00:00+00:00"

    def test_empty_incoming_preserves_everything(self):
        stored = {
            "items": [
                {
                    "id": "step-1",
                    "completed": True,
                    "completed_by": str(self.USER_A),
                    "completed_at": "2026-04-01T10:00:00+00:00",
                }
            ]
        }
        assert (
            merge_checklist_value(_checklist_field(), stored, {"items": []}, self.USER_B, self.NOW)
            == stored
        )


class TestChecklistInitialization:
    def test_missing_key_initialized_empty(self):
        result = initialize_checklist_values([_checklist_field()], {"other": 1})
        assert result["sop"] == {"items": []}
        assert result["other"] == 1

    def test_present_key_untouched(self):
        value = {"items": [{"id": "step-1", "completed": True}]}
        result = initialize_checklist_values([_checklist_field()], {"sop": value})
        assert result["sop"] == value
